@LiveMatchApi_Host = http://localhost:5000

GET {{LiveMatchApi_Host}}/
Accept: application/json

###

GET {{LiveMatchApi_Host}}/health
Accept: application/json

###

GET {{LiveMatchApi_Host}}/api/matches/live
Accept: application/json

###

GET {{LiveMatchApi_Host}}/api/matches/upcoming
Accept: application/json
